### PR TITLE
Tmds

### PR DESCRIPTION
**Pull request by Rauldg**
@planthaber What do you think? Is the acquisition of the plugin like this fine? If there is another standard, please let me know. Thanks

### CODE REVIEW

**Comment by planthaber** [comment]
Can we rename the task to something more meaningful that TDMS? like TetherSimulation or just Tether? 

I don't even know what TDMS stands for (and I am working in that project)

**Comment by Rauldg** [comment]
It stands for Tether Management and Docking System... Should we name it `tether_docking`? That name is also not that nice ...

**Comment by Rauldg** [comment]
I think we can leave it in tether

**Comment by Rauldg** [comment]
@planthaber Renaming applied

**Comment by planthaber** [comment]
mars_plugin_collection is an internal package, i need to revert this

**Comment by planthaber** [comment]
Please re-create a PR, after the plugin is available as opensource

**Pull request merged**
