### PR TITLE
Adapts to current MARS

### PR DESCRIPTION
**Pull request by shoppel**

### CODE REVIEW

**Comment by kavonszadkowski** [comment]
These changes are currently only compatible with the develop branch of rock-simulation/mars, thus this shouldn't be merged until develop is merged into master there.

**Comment by goldhoorn** [comment]
@shoppel : i think mars i merged now, coud you please rebase your PR?

**Comment by goldhoorn** [comment]
and please do not use "for <project>" anywhere. Describe what you commit does!

**Comment by jmachowinski** [comment]
this commit is broken

**Comment by jmachowinski** [comment]
The correct version can be found in the internat mars git on the spacebot2015 branch

**Comment by goldhoorn** [comment]
Can you then create a new PR and close this?


On 23.09.2015 17:50, jmachowinski wrote:
>
> The correct version can be found in the internat mars git on the 
> spacebot2015 branch
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rock-simulation/simulation-orogen-mars/pull/25#issuecomment-142645258>.
>


-- 
  Dipl.-Inf. Matthias Goldhoorn
  Space and Underwater Robotic

  Universität Bremen
  FB 3 - Mathematik und Informatik
  AG Robotik
  Robert-Hooke-Straße 1
  28359 Bremen, Germany
  
  Zentrale: +49 421 178 45-6611
  
  Besuchsadresse der Nebengeschäftstelle:
  Robert-Hooke-Straße 5
  28359 Bremen, Germany
  
  Tel.:    +49 421 178 45-4193
  Empfang: +49 421 178 45-6600
  Fax:     +49 421 178 45-4150
  E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

  Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by jmachowinski** [comment]
I don't have any rights on this repo, Kai must do it.

**Comment by goldhoorn** [comment]
He close  this but you can create a New  pr

**Pull request closed without merging**
