### PR TITLE
path_drawer

### PR DESCRIPTION
**Pull request by dettmann**
This module takes a 2d trajectory gets the the corresponding z-coordinates via ray tracing and draws the trajectory in mars. It also returns the corresponding 3d trajectory.
In addition it can draw a given waypoint.

Could anybody take a look at it?

### CODE REVIEW

**Comment by goldhoorn** [comment]
Sounds quite specific, not sure if this should become a "mars-sim-standard" module. 
This triggers again the question "all modules in one" or create separate modules.
This path drawer is a bit special, because it only affects the visualazion, and not the simulation itself...
I assume in the long-run this will replaced by the new mars-gui-system which is based on syskit.
In the meantime i thing we can accept this. 

Other meanings? 
maybe @jakobs?

**Comment by jakobs** [comment]
I am also a bit unsure about this. It mixes a lot of different concepts which imho we should try to separate. Is this for visualization? Then in my opinion it should be a vizkit plugin. If its for tracing the countour of an environment, it should be using envire. Mars in my opinion is a simulation. It happens to have a visualization attached to it (which we try to seperate and use only one, to avoid this kind of confusion), but using the rock interface to feed back visual information to mars seems strange to me.

**Comment by goldhoorn** [comment]
@dettmann you created a new package for this, right?,
this PR can then be closed or did i miss something?

**Comment by dettmann** [comment]
correct

**Pull request closed without merging**
